version: '3.7'

services:
  config:
    build:
      context: ./config
      dockerfile: Dockerfile
    expose:
      - "8888"
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - reverse-proxy-network

  monitoring:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - config
      - registry
    expose:
      - "9000"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - reverse-proxy-network
    
  registry:
    build:
      context: ./registry
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - config
    expose:
      - "8761"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - reverse-proxy-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - config
      - registry
    expose:
      - "8081"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - reverse-proxy-network
  
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - config
      - registry
    expose:
      - "80"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - reverse-proxy-network

  zipkin-mysql:
    image: openzipkin/zipkin-mysql
    networks:
      - reverse-proxy-network

  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-mysql
      - SELF_TRACING_ENABLED=true
      - SCRIBE_ENABLED=true
    expose:
      - "9411"
      - "9410"
    depends_on:
      - zipkin-mysql
    networks:
      - reverse-proxy-network

  prometheus:
    image: prom/prometheus
    expose:
      - "9090"
    depends_on:
      - zipkin-mysql
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - reverse-proxy-network

  grafana:
    image: grafana/grafana
    expose:
      - "3000"
    depends_on:
      - prometheus
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,novatec-sdg-panel,camptocamp-prometheus-alertmanager-datasource
    networks:
      - reverse-proxy-network

networks:
  reverse-proxy-network:
    name: reverse-proxy-network
    driver: bridge
