version: '3.7'

services:
  config:
    ports: 
      - 8888:8888
  monitoring:
    ports: 
      - 9000:9000
  registry:
    ports: 
      - 8761:8761
  admin:
    ports: 
      - 8081:8081
  gateway:
    ports: 
      - 80:80

networks:
  reverse-proxy-network:
    name: reverse-proxy-network
    driver: bridge