server:
  shutdown: graceful
  undertow:
    url-charset: UTF-8

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: authentication-service
  cloud:
    discovery:
      client:
        health-indicator:
          include-description: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://usermanagement-db:3306/${USERMANAGEMENT_DB}
  jpa:
    hibernate:
      dll-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    refresh:
      enable: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    git:
      mode: full