stages:
- name: Build and Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./microservice/admin/Dockerfile
      buildContext: .
      tag: michibaum/admin
  - publishImageConfig:
      dockerfilePath: ./microservice/gateway/Dockerfile
      buildContext: .
      tag: michibaum/gateway
  - publishImageConfig:
      dockerfilePath: ./microservice/registry/Dockerfile
      buildContext: .
      tag: michibaum/registry
- name: sdc
  steps:
  - applyYamlConfig:
      path: ./microservice/admin/deployment.yaml
  - applyYamlConfig:
      path: ./microservice/gateway/deployment.yaml
  - applyYamlConfig:
      path: ./microservice/registry/deployment.yaml
timeout: 60
notification: {}
