stages:
- name: Build and Publish
  steps:
  - runScriptConfig:
      image: openjdk:16-jdk-alpine3.13
      shellScript: ./microservice/admin/mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=michibaum/admin
  - runScriptConfig:
      image: openjdk:16-jdk-alpine3.13
      shellScript: ./microservice/gateway/mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=michibaum/gateway
  - runScriptConfig:
      image: openjdk:16-jdk-alpine3.13
      shellScript: ./microservice/registry/mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=michibaum/registry
- name: sdc
  steps:
  - applyYamlConfig:
      path: ./microservice/admin/deployment.yaml
  - applyYamlConfig:
      path: ./microservice/gateway/deployment.yaml
  - applyYamlConfig:
      path: ./microservice/registry/deployment.yaml
timeout: 60
notification: {}
