stages:
- name: Build and Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./microservice/admin/Dockerfile
      buildContext: ./microservice/admin
      tag: michibaum/admin
      registry: 127.0.0.1:34198
  - publishImageConfig:
      dockerfilePath: ./microservice/gateway/Dockerfile
      buildContext: ./microservice/gateway
      tag: michibaum/gateway
      registry: 127.0.0.1:34198
  - publishImageConfig:
      dockerfilePath: ./microservice/registry/Dockerfile
      buildContext: ./microservice/registry
      tag: michibaum/registry
      registry: 127.0.0.1:34198
- name: sdc
  steps:
  - applyYamlConfig:
      path: ./microservice/admin/deployment.yaml
  - applyYamlConfig:
      path: ./microservice/gateway/deployment.yaml
  - applyYamlConfig:
      path: ./microservice/registry/deployment.yaml
timeout: 60
notification: {}
