version: '3.7'

services:
  lifemanagement-backend:
    container_name: lifemanagement-backend
    restart: always
    ports:
    - "81:81"
    volumes:
    - /lifemanagement/backend/h2:/h2/lifemanagement
    build:
      context: ./backend/lifemanagement-backend
      dockerfile: Dockerfile
      args:
        profile: docker

  lifemanagement-frontend:
    container_name: lifemanagement-frontend
    restart: always
    ports:
    - "80:80"
    build:
      context: ./frontend/lifemanagement-frontend
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 3m
      timeout: 10s
      retries: 3
      start_period: 3m