version: '3.7'

services:

  registry-service:
    image: 70131370/registry-service:1.0.0-TEST-8
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - zipkin
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
    expose:
      - "8761"
    networks:
      - microservice-network

  admin-service:
    image: 70131370/admin-service:1.0.0-TEST-8
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
      - zipkin
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
    expose:
      - "80"
    networks:
      - microservice-network

  javadoc-service:
    image: 70131370/javadoc-service:1.0.0-TEST-8
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
      - zipkin
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
    expose:
      - "80"
    networks:
      - microservice-network

  authentication-service:
    image: 70131370/authentication-service:1.0.0-TEST-8
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
      - zipkin
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
    expose:
      - "80"
    networks:
      - microservice-network

  authentication-db:
    image: mysql:8.0
    env_file:
      - .env
      - .env.override
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTHENTICATION_DB_PASSWORD}
      MYSQL_DATABASE: ${AUTHENTICATION_DB}
    expose:
      - "3306"
    volumes:
      - /data/authentication-db:/var/lib/mysql
    networks:
      - microservice-network

  usermanagement-service:
    image: 70131370/usermanagement-service:1.0.0-TEST-8
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
      - usermanagement-db
      - zipkin
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
      DATABASE_PASSWORD: ${USERMANAGEMENT_DB_PASSWORD}
      DATABASE: ${USERMANAGEMENT_DB}
    expose:
      - "80"
    networks:
      - microservice-network

  usermanagement-db:
    image: mysql:8.0
    env_file:
      - .env
      - .env.override
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${USERMANAGEMENT_DB_PASSWORD}
      MYSQL_DATABASE: ${USERMANAGEMENT_DB}
    expose:
      - "3306"
    volumes:
      - /data/usermanagement-db:/var/lib/mysql
    networks:
      - microservice-network

  gateway-service:
    image: 70131370/gateway-service:1.0.0-TEST-8
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
      - zipkin
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
    ports:
      - "80:80"
    networks:
      - microservice-network

#  zipkin-service:
#    image: 70131370/zipkin-service:1.0.0-TEST-8
#    env_file:
#      - .env
#      - .env.override
#    restart: always
#    depends_on:
#      - registry-service
#    environment:
#      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
#    expose:
#      - "80"
#    networks:
#      - microservice-network

  zipkin-db:
    image: openzipkin/zipkin-mysql
    container_name: zipkin-db
    # ports:
    #   - 3306:3306

  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-db
      # Uncomment to enable scribe
      # - SCRIBE_ENABLED=true
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
    ports:
      - "9411:9411"
      # Uncomment if you set SCRIBE_ENABLED=true
      # - 9410:9410
    depends_on:
      - zipkin-db

  # Adds a cron to process spans since midnight every hour, and all spans each day
  # This data is served by http://192.168.99.100:8080/dependency
  #
  # For more details, see https://github.com/openzipkin/docker-zipkin-dependencies
  zipkin-dependencies:
    image: openzipkin/zipkin-dependencies
    container_name: zipkin-dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-db
      # Add the baked-in username and password for the zipkin-mysql image
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      # Uncomment to see dependency processing logs
      # - ZIPKIN_LOG_LEVEL=DEBUG
      # Uncomment to adjust memory used by the dependencies job
      # - JAVA_OPTS=-verbose:gc -Xms1G -Xmx1G
    depends_on:
      - zipkin-db


#  Matomo
# https://medium.com/@davquar/matomo-lets-install-it-with-docker-512211705c76
# https://github.com/matomo-org/docker

networks:
  microservice-network:
    name: microservice-network
    driver: bridge
