version: '3.4'

services:
  lifemanagement-backend:
    container_name: lifemanagement-backend
    hostname: lifemanagement-backend
    restart: always
    expose:
    - "80"
    volumes:
    - /lifemanagement/backend/h2:/h2/lifemanagement
    build:
      context: ./backend/lifemanagement-backend
      dockerfile: Dockerfile
      args:
        profile: docker
    network_mode: bridge

  lifemanagement-frontend:
    container_name: lifemanagement-frontend
    hostname: lifemanagement-frontend
    restart: always
    expose:
    - "80"
    build:
      context: ./frontend/lifemanagement-frontend
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 3m
      timeout: 10s
      retries: 3
      start_period: 3m
    network_mode: bridge