version: '3.7'

services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - microservice-network

  registry-service:
    image: 70131370/registry-service:1.0.0-TEST
    restart: always
    environment:
      - VIRTUAL_HOST=registry.michibaum.ch
      - VIRTUAL_PORT=8761
    expose:
      - "8761"
    networks:
      - microservice-network

  admin-service:
    image: 70131370/admin-service:1.0.0-TEST
    restart: always
    depends_on:
      - registry-service
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=admin.michibaum.ch
      - VIRTUAL_PORT=8080
    networks:
      - microservice-network

  javadoc-service:
    image: 70131370/javadoc-service:1.0.0-TEST
    restart: always
    depends_on:
      - registry-service
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=javadoc.michibaum.ch
      - VIRTUAL_PORT=8080
    networks:
      - microservice-network

  authentication-service:
    image: 70131370/authentication-service:1.0.0-TEST
    restart: always
    depends_on:
      - registry-service
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=authentication.michibaum.ch
      - VIRTUAL_PORT=8080
    networks:
      - microservice-network

  usermanagement-service:
    image: 70131370/usermanagement-service:1.0.0-TEST
    restart: always
    depends_on:
      - registry-service
      - usermanagement-db
    expose:
      - "8080"
    environment:
      VIRTUAL_HOST: usermanagement.michibaum.ch
      VIRTUAL_PORT: 8080
      DATABASE_PASSWORD: ${USERMANAGEMENT_DB_PASSWORD}
      DATABASE: ${USERMANAGEMENT_DB}
    networks:
      - microservice-network

  usermanagement-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${USERMANAGEMENT_DB_PASSWORD}
      MYSQL_DATABASE: ${USERMANAGEMENT_DB}
    expose:
      - "3306"
    volumes:
      - /data/usermanagement-db:/var/lib/mysql

#  Matomo
# https://medium.com/@davquar/matomo-lets-install-it-with-docker-512211705c76
# https://github.com/matomo-org/docker

networks:
  microservice-network:
    name: microservice-network
    driver: bridge
