version: '3.7'

services:
  lifemanagement-database:
    container_name: lifemanagement-database
    hostname: lifemanagement-database
    image: mysql:8.0.20
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: 'lifemanagement'
      MYSQL_USER: 'lifemanagement-user'
      MYSQL_PASSWORD: 'qwermnbvqw1212'
      MYSQL_ROOT_PASSWORD: 'root'
    networks: 
      - reverse-proxy-network

  lifemanagement-backend:
    container_name: lifemanagement-backend
    hostname: lifemanagement-backend
    restart: always
    depends_on: [lifemanagement-database]
    expose:
    - "80"
    build:
      context: ./backend/lifemanagement-backend
      dockerfile: Dockerfile
      args:
        profile: docker
    networks: 
      - reverse-proxy-network

  lifemanagement-frontend:
    container_name: lifemanagement-frontend
    hostname: lifemanagement-frontend
    restart: always
    expose:
    - "80"
    build:
      context: ./frontend/lifemanagement-frontend
      dockerfile: Dockerfile
    networks: 
      - reverse-proxy-network

networks:
  reverse-proxy-network:
      name: reverse-proxy-network