services:
  prometheus:
    build:
      dockerfile: prometheus/Dockerfile
    ports:
      - "9090:9090"
    environment:
      EUREKA_URL: http://admin_username:admin_password@host.docker.internal:8761/eureka
      EUREKA_USERNAME: admin_username
      EUREKA_PASSWORD: admin_password
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"