services:
  zipkin-storage:
    image: ghcr.io/openzipkin/zipkin-elasticsearch8:3.5
    env_file:
      - .local-env
    restart: always
    expose:
      - "9200"

  zipkin:
    image: ghcr.io/openzipkin/zipkin:3.5
    env_file:
      - .local-env
    restart: always
    depends_on:
      - zipkin-storage
    environment:
      STORAGE_TYPE: elasticsearch
      ES_HOSTS: zipkin-storage:9200
      # TODO EUREKA_SERVICE_URL doesnt work: WARN [/] 1 --- [orker-epoll-2-2] c.l.a.s.e.EurekaUpdatingListener: Failed to register zipkin to Eureka: http://registry.michibaum.ch:8761/eureka/v2
#      EUREKA_SERVICE_URL: http://registry.michibaum.ch:8761/eureka/v2
#      EUREKA_HOSTNAME: zipkin
    ports:
      - "9411:9411"

  zipkin-dependencies:
    image: ghcr.io/openzipkin/zipkin-dependencies:3.2
    env_file:
      - .local-env
    restart: always
    depends_on:
      - zipkin-storage
    user: root
    entrypoint: /usr/sbin/crond -f
    environment:
      STORAGE_TYPE: elasticsearch
      ES_HOSTS: zipkin-storage:9200

  prometheus:
    build:
      context: prometheus
      dockerfile: Dockerfile
    environment:
      PROMETHEUS_EUREKA_URL: http://admin_username:admin_password@host.docker.internal:8761/eureka
      PROMETHEUS_EUREKA_USERNAME: admin_username
      PROMETHEUS_EUREKA_PASSWORD: admin_password
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning