version: '3.7'

services:

  registry-service:
    image: 70131370/registry-service
    env_file:
      - .env
      - .env.override
    restart: always
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
    expose:
      - "8761"
    networks:
      - microservice-network

  admin-service:
    image: 70131370/admin-service
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
    expose:
      - "80"
    networks:
      - microservice-network

  authentication-service:
    image: 70131370/authentication-service
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
      DATABASE_USERNAME: ${AUTHENTICATION_DB_USERNAME}
      DATABASE_PASSWORD: ${AUTHENTICATION_DB_PASSWORD}
      DATABASE: ${AUTHENTICATION_DB}
    expose:
      - "80"
    networks:
      - microservice-network

  authentication-db:
    image: mariadb:lts-noble
    env_file:
      - .env
      - .env.override
    restart: always
    environment:
      MARIADB_USER: ${AUTHENTICATION_DB_USERNAME}
      MARIADB_PASSWORD: ${AUTHENTICATION_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${AUTHENTICATION_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${AUTHENTICATION_DB}
    expose:
      - "3306"
    volumes:
      - /data/authentication-db:/var/lib/mysql
    networks:
      - microservice-network

  usermanagement-service:
    image: 70131370/usermanagement-service
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
      - usermanagement-db
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
      DATABASE_USERNAME: ${USERMANAGEMENT_DB_USERNAME}
      DATABASE_PASSWORD: ${USERMANAGEMENT_DB_PASSWORD}
      DATABASE: ${USERMANAGEMENT_DB}
    expose:
      - "80"
    networks:
      - microservice-network

  usermanagement-db:
    image: mariadb:lts-noble
    env_file:
      - .env
      - .env.override
    restart: always
    environment:
      MARIADB_USER: ${USERMANAGEMENT_DB_USERNAME}
      MARIADB_PASSWORD: ${USERMANAGEMENT_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${USERMANAGEMENT_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${USERMANAGEMENT_DB}
    expose:
      - "3306"
    volumes:
      - /data/usermanagement-db:/var/lib/mysql
    networks:
      - microservice-network

  gateway-service:
    image: 70131370/gateway-service
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
    ports:
      - "443:443"
    volumes:
      - /data/ssl:/data/ssl
    networks:
      - microservice-network

  website-service:
    image: 70131370/website-service
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
    expose:
      - "80"
    networks:
      - microservice-network

  chess-service:
    image: 70131370/chess-service
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
      - chess-db
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
      DATABASE_USERNAME: ${CHESS_DB_USERNAME}
      DATABASE_PASSWORD: ${CHESS_DB_PASSWORD}
      DATABASE: ${CHESS_DB}
    expose:
      - "80"
    networks:
      - microservice-network

  chess-db:
    image: mariadb:lts-noble
    env_file:
      - .env
      - .env.override
    restart: always
    environment:
      MARIADB_USER: ${CHESS_DB_USERNAME}
      MARIADB_PASSWORD: ${CHESS_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${CHESS_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${CHESS_DB}
    expose:
      - "3306"
    volumes:
      - /data/chess-db:/var/lib/mysql
    networks:
      - microservice-network

  fitness-service:
    image: 70131370/fitness-service
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
      - fitness-db
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
      DATABASE_USERNAME: ${FITNESS_DB_USERNAME}
      DATABASE_PASSWORD: ${FITNESS_DB_PASSWORD}
      DATABASE: ${FITNESS_DB}
    expose:
      - "80"
    networks:
      - microservice-network

  fitness-db:
    image: mariadb:lts-noble
    env_file:
      - .env
      - .env.override
    restart: always
    environment:
      MARIADB_USER: ${FITNESS_DB_USERNAME}
      MARIADB_PASSWORD: ${FITNESS_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${FITNESS_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${FITNESS_DB}
    expose:
      - "3306"
    volumes:
      - /data/fitness-db:/var/lib/mysql
    networks:
      - microservice-network

#  Matomo
# https://medium.com/@davquar/matomo-lets-install-it-with-docker-512211705c76
# https://github.com/matomo-org/docker

networks:
  microservice-network:
    name: microservice-network
    driver: bridge
