version: '3.7'

services:
  lifemanagement-database:
    container_name: lifemanagement-database
    hostname: lifemanagement-database
    image: mysql:8.0.20
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: 'lifemanagement'
      MYSQL_USER: 'lifemanagement-user'
      MYSQL_PASSWORD: 'qwermnbvqw1212'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes: 
      - lifemanagement-database_backup:/var/lib/mysql
    networks: 
      - reverse-proxy-network

  lifemanagement-backend:
    container_name: lifemanagement-backend
    hostname: lifemanagement-backend
    restart: always
    expose:
    - "80"
    environment:
      WAIT_HOSTS: lifemanagement-database:3306
    build:
      context: ./backend/lifemanagement-backend
      dockerfile: Dockerfile
      args:
        profile: docker
    depends_on: 
      - lifemanagement-database
    networks: 
      - reverse-proxy-network

  lifemanagement-frontend:
    container_name: lifemanagement-frontend
    hostname: lifemanagement-frontend
    restart: always
    expose:
    - "80"
    build:
      context: ./frontend/lifemanagement-frontend
      dockerfile: Dockerfile
    depends_on: 
      - lifemanagement-backend
    networks: 
      - reverse-proxy-network

volumes: 
  lifemanagement-database_backup:
    driver_opts:
      type: none
      device: /docker/lifemanagement/database/backup/
      o: bind

networks:
  reverse-proxy-network:
      name: reverse-proxy-network