services:

  registry-service:
    image: 70131370/registry-service
    pull_policy: always
    env_file:
      - .env
    restart: always
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
    expose:
      - "8761"
    networks:
      - microservice-network

  admin-service:
    image: 70131370/admin-service
    pull_policy: always
    env_file:
      - .env
    restart: always
    depends_on:
      registry-service:
        condition: service_healthy
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
    expose:
      - "80"
    networks:
      - microservice-network

  authentication-service:
    image: 70131370/authentication-service
    pull_policy: always
    env_file:
      - .env
    restart: always
    depends_on:
      registry-service:
        condition: service_healthy
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
      DATABASE_USERNAME: ${AUTHENTICATION_DB_USERNAME}
      DATABASE_PASSWORD: ${AUTHENTICATION_DB_PASSWORD}
      DATABASE: ${AUTHENTICATION_DB}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
    expose:
      - "80"
    networks:
      - microservice-network

  authentication-db:
    image: mariadb:10.11
    env_file:
      - .env
    restart: always
    environment:
      MARIADB_USER: ${AUTHENTICATION_DB_USERNAME}
      MARIADB_PASSWORD: ${AUTHENTICATION_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${AUTHENTICATION_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${AUTHENTICATION_DB}
    expose:
      - "3306"
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - /data/authentication-db:/var/lib/mysql
    networks:
      - microservice-network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3

  usermanagement-service:
    image: 70131370/usermanagement-service
    pull_policy: always
    env_file:
      - .env
    restart: always
    depends_on:
      registry-service:
        condition: service_healthy
      usermanagement-db:
        condition: service_healthy
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
      DATABASE_USERNAME: ${USERMANAGEMENT_DB_USERNAME}
      DATABASE_PASSWORD: ${USERMANAGEMENT_DB_PASSWORD}
      DATABASE: ${USERMANAGEMENT_DB}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
    expose:
      - "80"
    networks:
      - microservice-network

  usermanagement-db:
    image: mariadb:10.11
    env_file:
      - .env
    restart: always
    environment:
      MARIADB_USER: ${USERMANAGEMENT_DB_USERNAME}
      MARIADB_PASSWORD: ${USERMANAGEMENT_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${USERMANAGEMENT_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${USERMANAGEMENT_DB}
    expose:
      - "3306"
    ports:
      - "127.0.0.1:3308:3306"
    volumes:
      - /data/usermanagement-db:/var/lib/mysql
    networks:
      - microservice-network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3

  gateway-service:
    image: 70131370/gateway-service
    pull_policy: always
    env_file:
      - .env
    restart: always
    depends_on:
      registry-service:
        condition: service_healthy
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
    ports:
      - "443:443"
    volumes:
      - /data/ssl:/data/ssl
    networks:
      - microservice-network

  website-service:
    image: 70131370/website-service
    pull_policy: always
    env_file:
      - .env
    restart: always
    depends_on:
      registry-service:
        condition: service_healthy
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
    expose:
      - "80"
    networks:
      - microservice-network

  chess-service:
    image: 70131370/chess-service
    pull_policy: always
    env_file:
      - .env
    restart: always
    depends_on:
      registry-service:
        condition: service_healthy
      chess-db:
        condition: service_healthy
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
      DATABASE_USERNAME: ${CHESS_DB_USERNAME}
      DATABASE_PASSWORD: ${CHESS_DB_PASSWORD}
      DATABASE: ${CHESS_DB}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
    expose:
      - "80"
    networks:
      - microservice-network

  chess-db:
    image: mariadb:10.11
    env_file:
      - .env
    restart: always
    environment:
      MARIADB_USER: ${CHESS_DB_USERNAME}
      MARIADB_PASSWORD: ${CHESS_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${CHESS_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${CHESS_DB}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
    expose:
      - "3306"
    ports:
      - "127.0.0.1:3309:3306"
    volumes:
      - /data/chess-db:/var/lib/mysql
    networks:
      - microservice-network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3

  fitness-service:
    image: 70131370/fitness-service
    pull_policy: always
    env_file:
      - .env
    restart: always
    depends_on:
      registry-service:
        condition: service_healthy
      fitness-db:
        condition: service_healthy
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
      DATABASE_USERNAME: ${FITNESS_DB_USERNAME}
      DATABASE_PASSWORD: ${FITNESS_DB_PASSWORD}
      DATABASE: ${FITNESS_DB}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
    expose:
      - "80"
    networks:
      - microservice-network

  fitness-db:
    image: mariadb:10.11
    env_file:
      - .env
    restart: always
    environment:
      MARIADB_USER: ${FITNESS_DB_USERNAME}
      MARIADB_PASSWORD: ${FITNESS_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${FITNESS_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${FITNESS_DB}
    expose:
      - "3306"
    ports:
      - "127.0.0.1:3310:3306"
    volumes:
      - /data/fitness-db:/var/lib/mysql
    networks:
      - microservice-network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3

  music-service:
    image: 70131370/music-service
    pull_policy: always
    env_file:
      - .env
    restart: always
    depends_on:
      registry-service:
        condition: service_healthy
      music-db:
        condition: service_healthy
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
      DATABASE_USERNAME: ${MUSIC_DB_USERNAME}
      DATABASE_PASSWORD: ${MUSIC_DB_PASSWORD}
      DATABASE: ${MUSIC_DB}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
    expose:
      - "80"
    networks:
      - microservice-network

  music-db:
    image: mariadb:10.11
    env_file:
      - .env
    restart: always
    environment:
      MARIADB_USER: ${MUSIC_DB_USERNAME}
      MARIADB_PASSWORD: ${MUSIC_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MUSIC_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MUSIC_DB}
    expose:
      - "3306"
    ports:
      - "127.0.0.1:3311:3306"
    volumes:
      - /data/music-db:/var/lib/mysql
    networks:
      - microservice-network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3

#  Matomo
# https://medium.com/@davquar/matomo-lets-install-it-with-docker-512211705c76
# https://github.com/matomo-org/docker

networks:
  microservice-network:
    name: microservice-network
    driver: bridge
