version: '3.7'

services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - microservice-network

  registry:
    image: registry:1.0.0-TEST
    restart: always
    environment:
      - VIRTUAL_HOST=registry.michibaum.ch
      - VIRTUAL_PORT=8761
    expose:
      - "8761"
    networks:
      - microservice-network

  admin:
    image: admin:1.0.0-TEST
    restart: always
    depends_on:
      - registry
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=admin.michibaum.ch
      - VIRTUAL_PORT=8080
    networks:
      - microservice-network

  javadoc:
    image: javadoc:1.0.0-TEST
    restart: always
    depends_on:
      - registry
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=javadoc.michibaum.ch
      - VIRTUAL_PORT=8080
    networks:
      - microservice-network

networks:
  microservice-network:
    name: microservice-network
    driver: bridge