version: '3.7'

services:

  registry-service:
    image: 70131370/registry-service:1.0.0-TEST-8
    env_file:
      - .env
      - .env.override
    restart: always
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
    expose:
      - "8761"
    networks:
      - microservice-network

  admin-service:
    image: 70131370/admin-service:1.0.0-TEST-8
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
    expose:
      - "80"
    networks:
      - microservice-network

  javadoc-service:
    image: 70131370/javadoc-service:1.0.0-TEST-8
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
    expose:
      - "80"
    networks:
      - microservice-network

  authentication-service:
    image: 70131370/authentication-service:1.0.0-TEST-8
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
    expose:
      - "80"
    networks:
      - microservice-network

  authentication-db:
    image: mysql:8.0
    env_file:
      - .env
      - .env.override
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTHENTICATION_DB_PASSWORD}
      MYSQL_DATABASE: ${AUTHENTICATION_DB}
    expose:
      - "3306"
    volumes:
      - /data/authentication-db:/var/lib/mysql
    networks:
      - microservice-network

  usermanagement-service:
    image: 70131370/usermanagement-service:1.0.0-TEST-8
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
      - usermanagement-db
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
      DATABASE_PASSWORD: ${USERMANAGEMENT_DB_PASSWORD}
      DATABASE: ${USERMANAGEMENT_DB}
    expose:
      - "80"
    networks:
      - microservice-network

  usermanagement-db:
    image: mysql:8.0
    env_file:
      - .env
      - .env.override
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${USERMANAGEMENT_DB_PASSWORD}
      MYSQL_DATABASE: ${USERMANAGEMENT_DB}
    expose:
      - "3306"
    volumes:
      - /data/usermanagement-db:/var/lib/mysql
    networks:
      - microservice-network

  gateway-service:
    image: 70131370/gateway-service:1.0.0-TEST-8
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
    ports:
      - "80:80"
    networks:
      - microservice-network

  zipkin-service:
    image: 70131370/zipkin-service:1.0.0-TEST-8
    env_file:
      - .env
      - .env.override
    restart: always
    depends_on:
      - registry-service
    environment:
      spring_profiles_active: ${SPRING_ACTIVE_PROFILES}
    expose:
      - "80"
    networks:
      - microservice-network

#  Matomo
# https://medium.com/@davquar/matomo-lets-install-it-with-docker-512211705c76
# https://github.com/matomo-org/docker

networks:
  microservice-network:
    name: microservice-network
    driver: bridge
