version: '3.7'

services:
  config:
    container_name: config
    build:
      context: ./config
      dockerfile: Dockerfile
    expose:
      - "8888"
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - reverse-proxy-network

  monitoring:
    container_name: monitoring
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - config
      - registry
    expose:
      - "9000"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - reverse-proxy-network
    
  registry:
    container_name: registry
    build:
      context: ./registry
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - config
    expose:
      - "8761"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - reverse-proxy-network

  admin:
    container_name: admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - config
      - registry
    expose:
      - "8081"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - reverse-proxy-network
  
  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - config
      - registry
    expose:
      - "80"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - reverse-proxy-network

  zipkinMysql:
    image: openzipkin/zipkin-mysql
    container_name: zipkinMysql
    expose: 
      - "3306"
    networks:
      - reverse-proxy-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkinMysql
      - SCRIBE_ENABLED=true
      - SELF_TRACING_ENABLED=true
      - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
    expose:
      - "9411"
      - "9410"
    depends_on:
      - zipkinMysql
    networks:
      - reverse-proxy-network

networks:
  reverse-proxy-network:
    name: reverse-proxy-network
    driver: bridge
