version: '3.7'

services:
  config:
    build:
      context: ./config
      dockerfile: Dockerfile
    expose:
      - "8888"
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - reverse-proxy-network

  monitoring:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - config
      - registry
    expose:
      - "9000"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - reverse-proxy-network
    
  registry:
    build:
      context: ./registry
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - config
    expose:
      - "8761"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - reverse-proxy-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - config
      - registry
    expose:
      - "8081"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - reverse-proxy-network
  
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - config
      - registry
    expose:
      - "80"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - reverse-proxy-network

networks:
  reverse-proxy-network:
    name: reverse-proxy-network
    driver: bridge
