server:
  port: 8081

spring:
  boot:
    admin:
      service:
        username: admin_username
        password: admin_password
      client:
        username: admin_username
        password: admin_password
  microservices:
    discord:
      enabled: true
      bot-token: ${DISCORD_BOT_TOKEN}
      guild-id: ${DISCORD_GUILD_ID}
      logging:
        enabled: true
        channel-id: ${DISCORD_WEBSITE_SERVICE_LOG_CHANNEL}

eureka:
  client:
    service-url:
      defaultZone: http://admin_username:admin_password@localhost:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
    export:
      enabled: true
