server:
  port: 80

spring:
  microservices:
    discord:
      enabled: true
      bot-token: ${DISCORD_BOT_TOKEN}
      guild-id: ${DISCORD_GUILD_ID}
      logging:
        enabled: true
        channel-id: ${DISCORD_WEBSITE_SERVICE_LOG_CHANNEL}

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka