server:
  shutdown: graceful
  undertow:
    url-charset: UTF-8
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
#  TODO Issue: https://github.com/MichiBaum/Microservices/issues/170
#  http2:
#    enabled: true

public-endpoints:
  package-names:
    - com.michibaum.websiteservice

spring:
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: website-service
  cloud:
    discovery:
      client:
        health-indicator:
          include-description: true
  main:
    allow-bean-definition-overriding: true

eureka:
  dashboard:
    enabled: true
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    refresh:
      enable: true

management:
  endpoints:
    access:
      default: unrestricted
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    git:
      mode: full
      enabled: true
    build:
      enabled: true
    defaults:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
    ssl:
      enabled: true