server:
  shutdown: graceful
  undertow:
    url-charset: UTF-8
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true

public-endpoints:
  package-names:
    - com.michibaum.websiteservice
  endpoints:
    - raw-path: /actuator/health/readiness
      request-method: GET
    - raw-path: /actuator/health/liveness
      request-method: GET

spring:
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: website-service
  cloud:
    discovery:
      client:
        health-indicator:
          include-description: true
    openfeign:
      lazy-attributes-resolution: true
      httpclient:
        disable-ssl-validation: true
      http2client:
        enabled: true
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    metadata-map:
      prometheus.path: /actuator/prometheus
    prefer-ip-address: true
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    refresh:
      enable: true

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  observations:
    annotations:
      enabled: true
  endpoints:
    access:
      default: unrestricted
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    git:
      mode: full
      enabled: true
    build:
      enabled: true
    defaults:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
    ssl:
      enabled: true