apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:11.6.2
        ports:
        - containerPort: 3000
        env:
        - name: GF_SERVER_DOMAIN
          value: "grafana.michibaum.ch"
        - name: GF_SERVER_CORS_ALLOWED_ORIGINS
          value: "*"
        - name: GF_SERVER_CORS_ALLOWED_METHODS
          value: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        - name: GF_SECURITY_COOKIE_SAMESITE
          value: "disabled"
        - name: GF_SECURITY_CSRF_TRUSTED_ORIGINS
          value: "grafana.michibaum.ch"
        - name: GF_SECURITY_ALLOW_EMBEDDING
          value: "true"
        - name: GF_AUTH_LOGIN_COOKIE_NAME
          value: "grafana_session"
        volumeMounts:
          - name: grafana-datasources
            mountPath: /etc/grafana/provisioning/datasources/
          - name: grafana-dashboards
            mountPath: /etc/grafana/provisioning/dashboards/
          - name: grafana-dashboards-volume
            mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
        - name: grafana-dashboards-volume
          persistentVolumeClaim:
            claimName: grafana-dashboards-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: microservices
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: microservices
data:
  datasource.yml: |
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
      - name: Zipkin
        type: zipkin
        access: proxy
        url: http://zipkin:9411
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: microservices
data:
  default.yml: |
    apiVersion: 1

    providers:
      - name: 'Main'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-dashboards-pvc
  namespace: microservices
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: grafana
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-dashboards-pv
  labels:
    type: local
    app: grafana
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 35591.hostserv.eu
  hostPath:
    path: "/data/grafana-dashboards"