apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: microservices
type: Opaque
stringData:
  # SSL
  SSL_KEYSTORE_PASSWORD: "PleaseChangeMe"
  
  # Admin Service
  ADMIN_SERVICE_USERNAME: "PleaseChangeMe"
  ADMIN_SERVICE_PASSWORD: "PleaseChangeMe"
  ADMIN_SERVICE_NOTIFY_DISCORD_CHANNEL: "PleaseChangeMe"
  
  # Discord
  DISCORD_BOT_TOKEN: "PleaseChangeMe"
  DISCORD_GUILD_ID: "PleaseChangeMe"
  DISCORD_REGISTRY_SERVICE_LOG_CHANNEL: "PleaseChangeMe"
  DISCORD_USERMANAGEMENT_SERVICE_LOG_CHANNEL: "PleaseChangeMe"
  DISCORD_WEBSITE_SERVICE_LOG_CHANNEL: "PleaseChangeMe"
  DISCORD_CHESS_SERVICE_LOG_CHANNEL: "PleaseChangeMe"
  DISCORD_GATEWAY_SERVICE_LOG_CHANNEL: "PleaseChangeMe"
  DISCORD_AUTHENTICATION_SERVICE_LOG_CHANNEL: "PleaseChangeMe"
  DISCORD_ADMIN_SERVICE_LOG_CHANNEL: "PleaseChangeMe"
  DISCORD_FITNESS_SERVICE_LOG_CHANNEL: "PleaseChangeMe"
  DISCORD_MUSIC_SERVICE_LOG_CHANNEL: "PleaseChangeMe"
  
  # Authentication DB
  AUTHENTICATION_DB_USERNAME: "PleaseChangeMe"
  AUTHENTICATION_DB_PASSWORD: "PleaseChangeMe"
  AUTHENTICATION_DB_ROOT_PASSWORD: "PleaseChangeMe"
  
  # User Management DB
  USERMANAGEMENT_DB_USERNAME: "PleaseChangeMe"
  USERMANAGEMENT_DB_PASSWORD: "PleaseChangeMe"
  USERMANAGEMENT_DB_ROOT_PASSWORD: "PleaseChangeMe"
  
  # Chess DB
  CHESS_DB_USERNAME: "PleaseChangeMe"
  CHESS_DB_PASSWORD: "PleaseChangeMe"
  CHESS_DB_ROOT_PASSWORD: "PleaseChangeMe"
  
  # Fitness DB
  FITNESS_DB_USERNAME: "PleaseChangeMe"
  FITNESS_DB_PASSWORD: "PleaseChangeMe"
  FITNESS_DB_ROOT_PASSWORD: "PleaseChangeMe"
  FITBIT_CLIENT_ID: "PleaseChangeMe"
  FITBIT_CLIENT_SECRET: "PleaseChangeMe"
  
  # Music DB
  MUSIC_DB_USERNAME: "PleaseChangeMe"
  MUSIC_DB_PASSWORD: "PleaseChangeMe"
  MUSIC_DB_ROOT_PASSWORD: "PleaseChangeMe"
  SPOTIFY_CLIENT_ID: "PleaseChangeMe"
  SPOTIFY_CLIENT_SECRET: "PleaseChangeMe"