server:
  port: 80

fitbit:
  oauth:
    client-id: ${FITBIT_CLIENT_ID}
    client-secret: ${FITBIT_CLIENT_SECRET}

spring:
  boot:
    admin:
      client:
        username: ${ADMIN_SERVICE_USERNAME}
        password: ${ADMIN_SERVICE_PASSWORD}
  microservices:
    discord:
      enabled: true
      bot-token: ${DISCORD_BOT_TOKEN}
      guild-id: ${DISCORD_GUILD_ID}
      logging:
        enabled: true
        channel-id: ${DISCORD_FITNESS_SERVICE_LOG_CHANNEL}

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka