server:
  port: 8086

fitbit:
  oauth:
    client-id: ${FITBIT_CLIENT_ID:}
    client-secret: ${FITBIT_CLIENT_SECRET:}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  datasource:
    username: root
    password: someRootPass
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fitness-db
  jpa:
    hibernate:
      ddl-auto: validate
  boot:
    admin:
      client:
        username: admin_username
        password: admin_password