server:
  port: 8086

fitbit:
  oauth:
    client-id: ${FITBIT_CLIENT_ID:}
    client-secret: ${FITBIT_CLIENT_SECRET:}

eureka:
  client:
    service-url:
      defaultZone: http://admin_username:admin_password@localhost:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0

spring:
  datasource:
    username: root
    password: someRootPass
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fitness-db
  boot:
    admin:
      service:
        username: admin_username
        password: admin_password
      client:
        username: admin_username
        password: admin_password