# https://prometheus.io/docs/prometheus/latest/configuration/configuration
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'eureka'
    scrape_interval: 10s
    eureka_sd_configs:
      - server: http://admin_username:admin_password@host.docker.internal:8761/eureka
    basic_auth:
      username: admin_username
      password: admin_password
    relabel_configs:
      - source_labels: [ __meta_eureka_app_name ]
        target_label: application
        action: replace
      - source_labels: [ __meta_eureka_app_instance_id ]
        target_label: instance
        action: replace
      - source_labels: [__meta_eureka_app_instance_id]
        regex: '^host\.docker\.internal:([^:]+):(\d+)$'
        replacement: 'host.docker.internal:$2'
        target_label: __address__
        action: replace
      - source_labels: [ __meta_eureka_app_instance_metadata_prometheus_path ]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
