server:
  shutdown: graceful
  undertow:
    url-charset: UTF-8

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: gateway
  cloud:
    gateway:
      fail-on-route-definition-error: false
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://keycloak/auth/realms/master/protocol/openid-connect/token
            authorization-uri: http://keycloak/auth/realms/master/protocol/openid-connect/auth
            userinfo-uri: http://keycloak/auth/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

management:
  cloudfoundry:
    enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    git:
      mode: full
