server:
  shutdown: graceful
  undertow:
    url-charset: UTF-8

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: gateway
  cloud:
    gateway:
      fail-on-route-definition-error: false
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://registry:8761/eureka/

management:
  cloudfoundry:
    enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    git:
      mode: full
