apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: microservices
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: admin:1.0.0-SNAPSHOT
        ports:
          - name: http-port
            containerPort: 8080
        securityContext:
          runAsRoot: true
          readOnlyRootFilesystem: false
          capabilities: { }
          privileged: true
          allowPrivilegeEscalation: true