apiVersion: v1
kind: Service
metadata:
  name: admin
  annotations:
    meta.helm.sh/release-name: microservices-k8s
    meta.helm.sh/release-namespace: microservices
  labels:
    app.kubernetes.io/managed-by: Helm
  namespace: microservices
spec:
  selector:
    app: admin
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None