apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: microservices
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: registry-port
      protocol: TCP
      port: 8761
      targetPort: 8761
  selector:
    app: registry