server:
  http2:
    enabled: true
  port: 8081
  undertow:
    url-charset: UTF-8

logging:
  file:
    path: /var/log
  config: classpath:logback.xml
  register-shutdown-hook: true

spring:
  zipkin:
    base-url: http://zipkin:9411/
    service:
      name: admin
  sleuth:
    sampler:
      probability: 1
    baggage:
      correlation-enabled: true
  boot:
    admin:
      hazelcast:
        enabled: true
      ui:
        title: Admin Server
      monitor:
        status-interval: 3s
        status-lifetime: 3s
        info-interval: 30s
        info-lifetime: 30s
        default-retries: 5
      client:
        auto-deregistration: true
        auto-registration: true
        enabled: true
        register-once: false
  application:
    name: admin

eureka:
  client:
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://registry:8761/eureka/

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      external-file: /var/log/spring/spring_log.log
    env:
      post:
        enabled: true
    health:
      show-details: always
