server:
  http2:
    enabled: true
  port: 8081
  undertow:
    url-charset: UTF-8

spring:
  boot:
    admin:
      monitor:
        status-interval: 3s
        status-lifetime: 3s
      client:
        auto-deregistration: true
        auto-registration: true
        enabled: true
        register-once: false
  application:
    name: admin

eureka:
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://registry:8761/eureka/

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
