server:
  http2:
    enabled: true
  port: ${MONITORING_PORT}
  undertow:
    url-charset: UTF-8

logging:
  file:
    path: /var/log
  config: classpath:logback.xml
  register-shutdown-hook: true

spring:
  zipkin:
    base-url: http://zipkin:${ZIPKIN_PORT_2}/
    service:
      name: monitoring
  sleuth:
    sampler:
      probability: 1
    baggage:
      correlation-enabled: true
  boot:
    admin:
      client:
        auto-deregistration: true
        auto-registration: true
        enabled: true
        register-once: false
  application:
    name: monitoring

eureka:
  client:
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://registry:${REGISTRY_PORT}/eureka/

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
