server:
  http2:
    enabled: true
  port: 8761
  undertow:
    url-charset: UTF-8

logging:
  file:
    path: /var/log
  config: classpath:logback.xml
  register-shutdown-hook: true

spring:
  zipkin:
    base-url: http://zipkin:9411/
    service:
      name: registry
  sleuth:
    sampler:
      probability: 1
    baggage:
      correlation-enabled: true
  boot:
    admin:
      client:
        auto-deregistration: true
        auto-registration: true
        enabled: true
        register-once: false
  application:
    name: registry

eureka:
  server:
    eviction-interval-timer-in-ms: 2000
    enableSelfPreservation: true
    wait-time-in-ms-when-sync-empty: 0
  instance:
    leaseRenewalIntervalInSeconds: 15
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      external-file: /var/log/spring/spring_log.log
    env:
      post:
        enabled: true
    health:
      show-details: always
