server:
  shutdown: graceful
  undertow:
    url-charset: UTF-8
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 1024

spring:
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: gateway-service
  cloud:
    gateway:
      routes: # TODO permission to Authentication
        - id: admin
          uri: lb://admin-service
          predicates:
            - Host=admin.michibaum.*
          filters:
            - Authentication
        - id: registry
          uri: lb://registry-service
          predicates:
            - Host=registry.michibaum.*
          filters:
            - Authentication
        - id: authentication
          uri: lb://authentication-service
          predicates:
            - Host=authentication.michibaum.*
        - id: usermanagement
          uri: lb://usermanagement-service
          predicates:
            - Host=usermanagement.michibaum.*
          filters:
            - Authentication
        - id: chess
          uri: lb://chess-service
          predicates:
            - Host=chess.michibaum.*
        - id: fitness
          uri: lb://fitness-service
          predicates:
            - Host=fitness.michibaum.*
        - id: music
          uri: lb://music-service
          predicates:
            - Host=music.michibaum.*
        - id: website
          uri: lb://website-service
          predicates:
            - Host=michibaum.*
    discovery:
      client:
        health-indicator:
          include-description: true
    openfeign:
      lazy-attributes-resolution: true
      httpclient:
        disable-ssl-validation: true

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  boot:
    admin:
      client:
        enabled: true
#        TODO ?
        username: admin
        password: admin

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    refresh:
      enable: true

management:
  endpoints:
    access:
      default: unrestricted
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    git:
      mode: full
      enabled: true
    build:
      enabled: true
    defaults:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
    ssl:
      enabled: true

robots-txt:
  crawlers:
    -
      user-agent: "*"
      allowed:
        - "/"
        - "/*"
  sitemaps:
    - "/sitemap.xml"
sitemap-xml:
  locations:
    - "/"
    - "/home"
    - "/login"
    - "/register"
    - "/about-me"
    - "/donate"
    - "/imprint"
    - "/chess"
    - "/chess/news"
    - "/chess/events"
  data-locations:
    - static-part: "/chess/events/{replace}"
      data-location: CHESS_EVENTS
    - static-part: "/chess/openings/{replace}"
      data-location: CHESS_OPENINGS