server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://admin_username:admin_password@localhost:8761/eureka

spring:
  boot:
    admin:
      service:
        username: admin_username
        password: admin_password
      client:
        username: admin_username
        password: admin_password

cors:
  allowed-origin-patterns:
    - http://michibaum.ch:[80,4200]
    - http://*.michibaum.ch:[80,4200]
    - http://michibaum.com:[80,4200]
    - http://*.michibaum.com:[80,4200]
    - http://michibaum.eu:[80,4200]
    - http://*.michibaum.eu:[80,4200]