server:
  port: 443
  ssl:
    enabled: true
    bundle: server

spring:
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: "michibaum"
          keystore:
            location: "/data/ssl/keystore.p12"
            password: ${SSL_KEYSTORE_PASSWORD}
            type: "PKCS12"
  boot:
    admin:
      service:
        username: ${ADMIN_SERVICE_USERNAME}
        password: ${ADMIN_SERVICE_PASSWORD}
      client:
        username: ${ADMIN_SERVICE_USERNAME}
        password: ${ADMIN_SERVICE_PASSWORD}
  cloud:
    discovery:
      client:
        simple:
          local:
            secure: true
  microservices:
    discord:
      enabled: true
      bot-token: ${DISCORD_BOT_TOKEN}
      guild-id: ${DISCORD_GUILD_ID}
      logging:
        enabled: true
        channel-id: ${DISCORD_GATEWAY_SERVICE_LOG_CHANNEL}

eureka:
  client:
    service-url:
      defaultZone: http://${ADMIN_SERVICE_USERNAME}:${ADMIN_SERVICE_PASSWORD}@registry-service:8761/eureka
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443

management:
  services:
    zipkin-url: http://zipkin:9411
    prometheus-url: http://prometheus:9090
    grafana-url: http://grafana:3000
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0

cors:
  allowed-origin-patterns:
    - https://michibaum.ch
    - https://*.michibaum.ch
    - https://michibaum.com
    - https://*.michibaum.com
    - https://michibaum.eu
    - https://*.michibaum.eu
    - https://michibaum.org
    - https://*.michibaum.org
    - https://michibaum.app
    - https://*.michibaum.app
    - https://michibaum.me
    - https://*.michibaum.me
    - https://michibaum.net
    - https://*.michibaum.net
    - https://michibaum.info
    - https://*.michibaum.info
    - https://michibaum.xyz
    - https://*.michibaum.xyz