server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "http://localhost:4200"
              - "http://michibaum.ch"
              - "http://*.michibaum.ch"
            allowed-headers:
              - "*"
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS