server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  boot:
    admin:
      client:
        username: admin_username
        password: admin_password