server:
  port: 443
  ssl:
    bundle: "server"
    enabled: true
  http2:
    enabled: true

spring:
  boot:
    admin:
      client:
        username: ${ADMIN_SERVICE_USERNAME}
        password: ${ADMIN_SERVICE_PASSWORD}
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "https://michibaum.ch"
              - "https://*.michibaum.ch"
            allowed-headers:
              - "*"
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
    discovery:
      client:
        simple:
          local:
            secure: true
  microservices:
    discord:
      enabled: true
      bot-token: ${DISCORD_BOT_TOKEN}
      guild-id: ${DISCORD_GUILD_ID}
      logging:
        enabled: true
        channel-id: ${DISCORD_GATEWAY_SERVICE_LOG_CHANNEL}
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: "michibaum"
          keystore:
            location: "/data/ssl/keystore.p12"
            password: ${SSL_KEYSTORE_PASSWORD}
            type: "PKCS12"

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true