server:
  shutdown: graceful
  undertow:
    url-charset: UTF-8
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 2048

spring:
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: admin
          uri: lb://admin-service
          predicates:
            - Host=admin.michibaum.ch
          filters:
            - Authentication
        - id: registry
          uri: lb://registry-service
          predicates:
            - Host=registry.michibaum.ch
          filters:
            - Authentication
        - id: authentication
          uri: lb://authentication-service
          predicates:
            - Host=authentication.michibaum.ch
        - id: usermanagement
          uri: lb://usermanagement-service
          predicates:
            - Host=usermanagement.michibaum.ch
          filters:
            - Authentication
        - id: chess
          uri: lb://chess-service
          predicates:
            - Host=chess.michibaum.ch
        - id: fitness
          uri: lb://fitness-service
          predicates:
            - Host=fitness.michibaum.ch
        - id: music
          uri: lb://music-service
          predicates:
            - Host=music.michibaum.ch
        - id: website
          uri: lb://website-service
          predicates:
            - Host=michibaum.ch
    discovery:
      client:
        health-indicator:
          include-description: true
    openfeign:
      lazy-attributes-resolution: true
      httpclient:
        disable-ssl-validation: true

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  boot:
    admin:
      client:
        enabled: true
#        TODO ?
        username: admin
        password: admin

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    refresh:
      enable: true

management:
  endpoints:
    access:
      default: unrestricted
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    git:
      mode: full
      enabled: true
    build:
      enabled: true
    defaults:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
    ssl:
      enabled: true