server:
  shutdown: graceful
  undertow:
    url-charset: UTF-8

spring:
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "http://michibaum.ch"
            allowed-headers:
              - "*"
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: admin
          uri: lb://admin-service
          predicates:
            - Host=admin.michibaum.ch
#          filters:
#            - Authentication
        - id: authentication
          uri: lb://authentication-service
          predicates:
            - Host=authentication.michibaum.ch
        - id: usermanagement
          uri: lb://usermanagement-service
          predicates:
            - Host=usermanagement.michibaum.ch
          filters:
            - Authentication
        - id: chess
          uri: lb://chess-service
          predicates:
            - Host=chess.michibaum.ch
          filters:
            - Authentication
        - id: fitness
          uri: lb://fitness-service
          predicates:
            - Host=fitness.michibaum.ch
          filters:
            - Authentication
        - id: website
          uri: lb://website-service
          predicates:
            - Host=michibaum.ch
    discovery:
      client:
        health-indicator:
          include-description: true
    openfeign:
      lazy-attributes-resolution: true

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  boot:
    admin:
      client:
        enabled: true
#        ?
        username: admin
        password: admin

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    refresh:
      enable: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    git:
      mode: full
