server:
  shutdown: graceful
  undertow:
    url-charset: UTF-8
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 1024
#  TODO Issue: https://github.com/MichiBaum/Microservices/issues/170
#  http2:
#    enabled: true

public-endpoints:
  package-names:
    - com.michibaum.gatewayservice
  endpoints:
    - raw-path: /actuator/health/readiness
      request-method: GET

spring:
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: gateway-service
  cloud:
    discovery:
      client:
        health-indicator:
          include-description: true
    openfeign:
      lazy-attributes-resolution: true
      httpclient:
        disable-ssl-validation: true
      http2client:
        enabled: true
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    metadata-map:
      prometheus.path: /actuator/prometheus
    prefer-ip-address: true
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    refresh:
      enable: true
    restclient:
      enabled: true

management:
  server:
    port: 80
    ssl:
      enabled: false
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  observations:
    annotations:
      enabled: true
  endpoints:
    access:
      default: unrestricted
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    git:
      mode: full
      enabled: true
    build:
      enabled: true
    defaults:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
    ssl:
      enabled: true

robots-txt:
  crawlers:
    -
      user-agent: "*"
      allowed:
        - "/"
        - "/*"
  sitemaps:
    - "/sitemap.xml"
sitemap-xml:
  locations:
    - "/"
    - "/home"
    - "/login"
    - "/register"
    - "/about-me"
    - "/donate"
    - "/imprint"
    - "/chess"
    - "/chess/news"
    - "/chess/events"
  data-locations:
    - static-part: "/chess/events/{replace}"
      data-location: CHESS_EVENTS
    - static-part: "/chess/openings/{replace}"
      data-location: CHESS_OPENINGS