server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  boot:
    admin:
      client:
        username: admin_username
        password: admin_password

cors:
  allowed-origin-patterns:
    - http://michibaum.ch:4200
    - http://michibaum.com:4200
    - http://michibaum.eu:4200