server:
  port: ${ADMIN_PORT}
  undertow:
    url-charset: UTF-8

spring:
  zipkin:
    base-url: ${ZIPKIN_BASE_URL}
    service:
      name: admin
  sleuth:
    sampler:
      probability: 1
    baggage:
      correlation-enabled: true
  boot:
    admin:
      hazelcast:
        enabled: true
      ui:
        title: Admin Server
      monitor:
        status-interval: 3s
        status-lifetime: 3s
        info-interval: 20s
        info-lifetime: 20s
        default-retries: 3
  application:
    name: admin

eureka:
  client:
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: ${REGISTRY_SERVICE_URL}

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
