server:
  http2:
    enabled: true
  port: 9000
  undertow:
    url-charset: UTF-8

spring:
  application:
    name: monitoring

eureka:
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
