### STAGE 1: Build ###
FROM node:13.10.1-alpine AS build
MAINTAINER Michael Baumberger
WORKDIR /usr/src/app
COPY ../frontend/lifemanagement-frontend/package.json ./
RUN npm install npm@latest -g
COPY ../frontend/lifemanagement-frontend/ .
RUN npm run build -- --prod

### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
MAINTAINER Michael Baumberger
COPY --from=build /usr/src/app/dist/lifemanagement-frontend /usr/share/nginx/html
