### STAGE 1: Package ###
FROM maven:3.6.2-jdk-11-slim AS MAVEN_BUILD
MAINTAINER Michael Baumberger
ARG profile=docker-test
RUN echo 'ACTIVE PROFILE IS: $profile'
COPY ../backend/lifemanagement-backend/pom.xml /build/
COPY ../backend/lifemanagement-backend/src /build/src/
WORKDIR /build/
RUN mvn package -P $profile

### STAGE 2: Run ###
FROM openjdk:11-jre-slim
MAINTAINER Michael Baumberger
WORKDIR /app
COPY --from=MAVEN_BUILD /build/target/lifemanagement.jar /app/
ENTRYPOINT ["java", "-jar", "lifemanagement.jar"]
