spring:
  boot:
    admin:
      service:
        username: admin_username
        password: admin_password
      client:
        username: admin_username
        password: admin_password

eureka:
  client:
    service-url:
      defaultZone: http://admin_username:admin_password@localhost:8761/eureka
  environment: dev

management:
  zipkin:
    tracing:
      export:
        enabled: false
  tracing:
    enabled: false
    sampling:
      probability: 1.0