spring:
  boot:
    admin:
      client:
        username: admin_username
        password: admin_password

eureka:
  client:
    service-url:
      defaultZone: http://admin_username:admin_password@localhost:8761/eureka
  environment: dev