server:
  ssl:
    bundle: “web-server”
    client-auth: WANT

spring:
  microservices:
    discord:
      enabled: true
      bot-token: ${DISCORD_BOT_TOKEN}
      guild-id: ${DISCORD_GUILD_ID}
      logging:
        enabled: true
        channel-id: ${DISCORD_REGISTRY_SERVICE_LOG_CHANNEL}
  ssl:
    bundle:
      jks:
        web-server:
          key:
            alias: "michibaum"
          keystore:
            location: "/data/ssl/keystore.p12"
            password: ${SSL_KEYSTORE_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka