server:
  shutdown: graceful
  undertow:
    url-charset: UTF-8
  port: 8761

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: registry-service
  cloud:
    discovery:
      client:
        health-indicator:
          include-description: true
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    git:
      mode: full