apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: microservices
  annotations:
    meta.helm.sh/release-name: microservices-k8s
    meta.helm.sh/release-namespace: microservices
  labels:
    app.kubernetes.io/managed-by: Helm
  namespace: fleet-local
spec:
  branch: refactoring
  insecureSkipTLSVerify: false
  paths:
    - /k8s
  repo: 'https://github.com/MichiBaum/Microservices.git'
  targets:
    - clusterSelector: {}