server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://admin_username:admin_password@localhost:8761/eureka

spring:
  datasource:
    username: root
    password: someRootPass
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/authentication-db
  jpa:
    hibernate:
      ddl-auto: validate
  boot:
    admin:
      client:
        username: admin_username
        password: admin_password