server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://admin_username:admin_password@localhost:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

spring:
  datasource:
    username: root
    password: someRootPass
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/authentication-db
  boot:
    admin:
      service:
        username: admin_username
        password: admin_password
      client:
        username: admin_username
        password: admin_password