server:
  shutdown: graceful
  undertow:
    url-charset: UTF-8

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  boot:
    admin:
      hazelcast:
        enabled: true
      ui:
        title: Admin Server
        #public-url: ${ADMIN_PUBLIC_URL}
      monitor:
        status-interval: 3s
        status-lifetime: 3s
        info-interval: 20s
        info-lifetime: 20s
        default-retries: 3
  application:
    name: admin

eureka:
  client:
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://registry:8761/eureka/

management:
  cloudfoundry:
    enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    git:
      mode: full
