server:
  shutdown: graceful
  undertow:
    url-charset: UTF-8

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  boot:
    admin:
      hazelcast:
        enabled: true
      ui:
        title: Admin Server
        # Public URL because of Gateway
        # public-url: https://microservices.michibaum.ch/admin/
      monitor:
        status-interval: 3s
        status-lifetime: 3s
        info-interval: 20s
        info-lifetime: 20s
        default-retries: 3
  application:
    name: admin
  security:
    oauth2:
      client:
        registration:
          admin:
            provider: keycloak
            client-id: admin-service
            client-authentication-method: none
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: https://keycloak.michibaum.ch
  cloud:
    gcp:
      logging:
        enabled: true
      trace:
        pubsub:
          enabled: true
    kubernetes:
      reload:
        enabled: true
    discovery:
      client:
        health-indicator:
          include-description: true
  sleuth:
    sampler:
      probability: 1.0
  main:
    allow-bean-definition-overriding: true

management:
  cloudfoundry:
    enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    git:
      mode: full
