server:
  port: ${REGISTRY_PORT}
  shutdown: graceful
  undertow:
    url-charset: UTF-8

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  zipkin:
    base-url: ${ZIPKIN_BASE_URL}
    service:
      name: registry
  sleuth:
    sampler:
      probability: 1
    baggage:
      correlation-enabled: true
  application:
    name: registry

eureka:
  server:
    eviction-interval-timer-in-ms: 2000
    enableSelfPreservation: true
    wait-time-in-ms-when-sync-empty: 0
  instance:
    leaseRenewalIntervalInSeconds: 15
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
  dashboard:
    enabled: true

management:
  cloudfoundry:
    enabled: false
  metrics:
    export:
      elastic:
        host: ${ACTUATOR_ELASTICSEARCH_URL}
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    git:
      mode: full
