apiVersion: apps/v1
kind: Deployment
metadata:
  name: javadoc-deployment
  namespace: microservices
  labels:
    app: javadoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javadoc
  template:
    metadata:
      labels:
        app: javadoc
    spec:
      containers:
      - name: javadoc
        image: 70131370/javadoc:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        env:
          - name: GOOGLE_CLOUD_PROJECT
            valueFrom:
              configMapKeyRef:
                name: gcp-projectname
                # Specify the key associated with the value
                key: GOOGLE_CLOUD_PROJECT
        ports:
          - name: http-port
            containerPort: 8080
