apiVersion: v1
kind: Service
metadata:
  name: javadoc-svc
  namespace: microservices
spec:
  selector:
    app: javadoc
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
