server:
  port: ${MONITORING_PORT}
  undertow:
    url-charset: UTF-8

spring:
  zipkin:
    base-url: http://zipkin:${ZIPKIN_PORT_2}/
    service:
      name: monitoring
  sleuth:
    sampler:
      probability: 1
    baggage:
      correlation-enabled: true
  application:
    name: monitoring

eureka:
  client:
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://registry:${REGISTRY_PORT}/eureka/

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
