server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://admin_username:admin_password@localhost:8761/eureka

spring:
  boot:
    admin:
      service:
        username: admin_username
        password: admin_password
      ui:
        public-url: http://admin.michibaum.ch:80
      notify:
        custom-discord:
          enabled: false
      instance-auth:
        default-user-name: admin_username
        default-password: admin_password
        enabled: true

management:
  zipkin:
    tracing:
      export:
        enabled: false
  tracing:
    enabled: false
    sampling:
      probability: 1.0