server:
  port: 8082

spring:
  boot:
    admin:
      ui:
        public-url: http://admin.michibaum.ch
      #        public-url: http://localhost:8082
      notify:
        custom-discord:
          enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
