server:
  port: 80

spring:
  microservices:
    discord:
      enabled: true
      bot-token: ${DISCORD_BOT_TOKEN}
      guild-id: ${DISCORD_GUILD_ID}
      logging:
        enabled: true
        channel-id: ${DISCORD_ADMIN_SERVICE_LOG_CHANNEL}
  boot:
    admin:
      service:
        username: ${ADMIN_SERVICE_USERNAME}
        password: ${ADMIN_SERVICE_PASSWORD}
      ui:
        public-url: https://admin.michibaum.ch:443
      instance-auth:
        default-user-name: ${ADMIN_SERVICE_USERNAME}
        default-password: ${ADMIN_SERVICE_PASSWORD}
        enabled: true
      notify:
        custom-discord:
          enabled: true
          channel-id: ${ADMIN_SERVICE_NOTIFY_DISCORD_CHANNEL}
eureka:
  client:
    service-url:
      defaultZone: http://${ADMIN_SERVICE_USERNAME}:${ADMIN_SERVICE_PASSWORD}@registry-service:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans