server:
  port: 80

spring:
  microservices:
    discord:
      enabled: true
      bot-token: ${DISCORD_BOT_TOKEN}
      guild-id: ${DISCORD_GUILD_ID}
      logging:
        enabled: true
        channel-id: ${DISCORD_ADMIN_SERVICE_LOG_CHANNEL}
  boot:
    admin:
      ui:
        public-url: https://admin.michibaum.ch
      instance-auth:
        default-user-name: ${ADMIN_SERVICE_USERNAME}
        default-password: ${ADMIN_SERVICE_PASSWORD}
        enabled: true
      notify:
        custom-discord:
          enabled: true
          channel-id: ${ADMIN_SERVICE_NOTIFY_DISCORD_CHANNEL}
eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka