server:
  port: 8082

spring:
  boot:
    admin:
      ui:
          public-url: http://localhost:8082
      notify:
        custom-discord:
          enabled: false
      instance-auth:
        default-user-name: admin_username
        default-password: admin_password
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
