server:
  http2:
    enabled: true
  port: ${GATEWAY_PORT}
  undertow:
    url-charset: UTF-8

logging:
  file:
    path: /var/log
  config: classpath:logback.xml
  register-shutdown-hook: true

spring:
  zipkin:
    base-url: http://zipkin:${ZIPKIN_PORT_2}/
    service:
      name: gateway
  sleuth:
    sampler:
      probability: 1
    baggage:
      correlation-enabled: true
  boot:
    admin:
      client:
        auto-deregistration: true
        auto-registration: true
        enabled: true
        register-once: false
  application:
    name: gateway

eureka:
  client:
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://registry:${REGISTRY_PORT}/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    admin:
      path: /admin/**
      url: http://admin:${ADMIN_PORT}
    monitoring:
      path: /monitoring/**
      url: http://monitoring:${MONITORING_PORT}
    registry:
      path: /registry/**
      url: http://registry:${REGISTRY_PORT}

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
