export enum Permissions {
    ADMIN_SERVICE,
    ADMIN_SERVICE_CAN_SEND_REQUEST,

    REGISTRY_SERVICE,

    AUTHENTICATION_SERVICE,

    USERMANAGEMENT_SERVICE,
    USERMANAGEMENT_SERVICE_EDIT_OWN_USER,
    SERMANAGEMENT_SERVICE_EDIT_ALL_USER,

    JAVADOC_SERVICE,

    CHESS_SERVICE
}
