export enum Permissions {
    ADMIN_SERVICE,

    REGISTRY_SERVICE,

    AUTHENTICATION_SERVICE,

    USERMANAGEMENT_SERVICE,
    USERMANAGEMENT_SERVICE_EDIT_OWN_USER,
    SERMANAGEMENT_SERVICE_EDIT_ALL_USER,

    CHESS_SERVICE
}
