apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin
  namespace: microservices
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: admin-ip
    cert-manager.io/cluster-issuer: microservices-letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
  - host: admin.michibaum.ch
    http:
      paths:
      - backend:
          service:
            port:
              number: 8080
            name: admin
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - admin.michibaum.ch
    secretName: admin.michibaum.ch