apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: microservices
  annotations:
    cloud.google.com/neg: '{"ingress": false}'
spec:
  selector:
    app: admin
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None