apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: microservices
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: 70131370/admin:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        env:
          - name: GOOGLE_CLOUD_PROJECT
            valueFrom:
              configMapKeyRef:
                name: gcp-projectname
                # Specify the key associated with the value
                key: GOOGLE_CLOUD_PROJECT
        ports:
          - name: http-port
            containerPort: 8080
