version: '3.7'

services:
  shell:
    restart: always
    expose:
    - "80"
    build:
      context: ./shell
      dockerfile: Dockerfile
    networks: 
      - reverse-proxy-network

networks:
  reverse-proxy-network:
      name: reverse-proxy-network