apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  namespace: microservices
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: microservices-k8s
        meta.helm.sh/release-namespace: microservices
      labels:
        app.kubernetes.io/managed-by: Helm
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:14.0.0
        imagePullPolicy: Always
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
