apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-storage
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-storage
  template:
    metadata:
      labels:
        app: zipkin-storage
    spec:
      nodeSelector:
        kubernetes.io/hostname: 35591.hostserv.eu
      containers:
      - name: zipkin-storage
        image: ghcr.io/openzipkin/zipkin-elasticsearch8:3.5
        ports:
        - containerPort: 9200
        env:
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: ZIPKIN_DB_JAVA_TOOL_OPTIONS
        volumeMounts:
        - name: zipkin-storage-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: zipkin-storage-data
        persistentVolumeClaim:
          claimName: zipkin-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-storage
  namespace: microservices
spec:
  selector:
    app: zipkin-storage
  ports:
  - port: 9200
    targetPort: 9200
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: ghcr.io/openzipkin/zipkin:3.5
        ports:
        - containerPort: 9411
        env:
        - name: STORAGE_TYPE
          value: "elasticsearch"
        - name: ES_HOSTS
          value: "zipkin-storage:9200"
      initContainers:
      - name: wait-for-elasticsearch
        image: busybox
        command: ['sh', '-c', 'until nc -z zipkin-storage 9200; do echo waiting for zipkin-storage; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: microservices
spec:
  selector:
    app: zipkin
  ports:
  - port: 9411
    targetPort: 9411
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-dependencies
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-dependencies
  template:
    metadata:
      labels:
        app: zipkin-dependencies
    spec:
      containers:
      - name: zipkin-dependencies
        image: ghcr.io/openzipkin/zipkin-dependencies:3.2
        env:
        - name: STORAGE_TYPE
          value: "elasticsearch"
        - name: ES_HOSTS
          value: "zipkin-storage:9200"
        command: ["/usr/sbin/crond", "-f"]
        securityContext:
          runAsUser: 0
      initContainers:
      - name: wait-for-elasticsearch
        image: busybox
        command: ['sh', '-c', 'until nc -z zipkin-storage 9200; do echo waiting for zipkin-storage; sleep 2; done;']