apiVersion: v1
kind: Service
metadata:
  name: wireguard-${userName}-service
  namespace: ${namespace}
  labels:
    app: wireguard
    user: ${userName}
    managed-by: vpn-service
spec:
  type: NodePort
  selector:
    app: wireguard
    user: ${userName}
  ports:
  - name: wireguard
    protocol: UDP
    port: 51820
    targetPort: 51820
