server:
  http2:
    enabled: true
  port: 8888
  undertow:
    url-charset: UTF-8

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  application:
    name: config_server
  profiles:
    active: native
  security:
    user:
      name: system
      password: ${CONFIG_SERVICE_PASSWORD}

eureka:
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
