server:
  http2:
    enabled: true
  port: 8888
  undertow:
    url-charset: UTF-8

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
          add-label-locations: false
  application:
    name: config
  profiles:
    active: native
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
