server:
  port: ${REGISTRY_PORT}
  undertow:
    url-charset: UTF-8

spring:
  zipkin:
    base-url: ${ZIPKIN_BASE_URL}
    service:
      name: registry
  sleuth:
    sampler:
      probability: 1
    baggage:
      correlation-enabled: true
  application:
    name: registry

eureka:
  server:
    eviction-interval-timer-in-ms: 2000
    enableSelfPreservation: true
    wait-time-in-ms-when-sync-empty: 0
  instance:
    leaseRenewalIntervalInSeconds: 15
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
  dashboard:
    enabled: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
