apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: microservices
spec:
  selector:
    app: keycloak
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  sessionAffinity: None
