name: Build and Publish

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: 'Build, upload docker containers and deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Angular install
        run: npm --prefix ./website install ./website

      - name: Angular build
        run: npm run --prefix website build-production

      - name: Maven package
        run: mvn package -Ppublish-image -DdockerHub.username=${{secrets.DOCKER_USERNAME}} -DdockerHub.password=${{secrets.DOCKER_PASSWORD}}