name: Build and Publish

on: [push, pull_request]

jobs:
  build:
    name: 'Build, upload docker containers and deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Generate Javadoc
        run: mvn javadoc:aggregate

      - name: Maven Clean install
#        Windows: ./mvnw clean install "-DdockerHub.username=${{secrets.DOCKER_USERNAME}}" "-DdockerHub.password=${{secrets.DOCKER_PASSWORD}}"
        run: mvn clean install -DdockerHub.username=${{secrets.DOCKER_USERNAME}} -DdockerHub.password=${{secrets.DOCKER_PASSWORD}} -DdockerHub.publish=true

#      - name: Build & Publish docker images
#        run: mvn spring-boot:build-image --projects ./gateway-service,./admin-service,./javadoc-service,./registry-service,./usermanagement-service,./authentication-service -DdockerHub.username=${{secrets.DOCKER_USERNAME}} -DdockerHub.password=${{secrets.DOCKER_PASSWORD}}