name: Build and Publish

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: 'Build, upload docker containers and deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Generate Javadoc
        run: mvn javadoc:aggregate
      - name: Maven Clean install
        run: mvn clean install -DdockerHub.username=${{secrets.DOCKER_USERNAME}} -DdockerHub.password=${{secrets.DOCKER_PASSWORD}}
      - name: Build & Publish docker images
        run: mvn spring-boot:build-image --projects ./gateway-service,./admin-service,./javadoc-service,./registry-service,./usermanagement-service,./authentication-service -DdockerHub.username=${{secrets.DOCKER_USERNAME}} -DdockerHub.password=${{secrets.DOCKER_PASSWORD}}
