name: Build and Publish
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: 'Maven: Build and upload docker containers'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Generate Javadoc
        run: mvn javadoc:aggregate
      - name: Build & Publish docker images
        run: mvn spring-boot:build-image --projects ./admin-service,./javadoc-service,./registry-service -DdockerHub.username=${{secrets.DOCKER_USERNAME}} -DdockerHub.password=${{secrets.DOCKER_PASSWORD}}
