name: Build and Publish
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: 'Maven: Build and upload docker containers'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        # TODO joschi/setup-jdk@v2 isn't that popular and should be changed to actions/setup-java@v2 but they don't support java 16
        uses: joschi/setup-jdk@v2
        with:
          java-version: '17' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'
      - name: Generate Javadoc
        run: mvn javadoc:aggregate
      - name: Build & Publish docker images
        run: mvn spring-boot:build-image --projects ./admin-service,./javadoc-service,./registry-service -DdockerHub.username=${{secrets.DOCKER_USERNAME}} -DdockerHub.password=${{secrets.DOCKER_PASSWORD}}
