server:
  port: 8087

spotify:
  oauth:
    client-id: ${SPOTIFY_CLIENT_ID:}
    client-secret: ${SPOTIFY_CLIENT_SECRET:}

eureka:
  client:
    service-url:
      defaultZone: http://admin_username:admin_password@localhost:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0

spring:
  datasource:
    username: root
    password: someRootPass
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/music-db
  jpa:
    show-sql: true
  boot:
    admin:
      service:
        username: admin_username
        password: admin_password
      client:
        username: admin_username
        password: admin_password